from rocker/rstudio
MAINTAINER ReCoDE Project ( Bethan Cracknell-Daniels and Liam Gao )

LABEL software.version="1.0"

LABEL version="1.0"

LABEL software="IDMS"

WORKDIR /home/rstudio

RUN apt update && \
    apt-get install -y software-properties-common && \
    add-apt-repository ppa:marutter/rrutter4.0 && \
    add-apt-repository ppa:c2d4u.team/c2d4u4.0+ && \
    apt update && apt install -y r-cran-rstan

RUN R -e "install.packages(c('highr', 'devtools', 'stringr','yaml' ))" && \
    R -e "devtools::install_version('bayesplot', '1.8.1')" && \
    R -e "devtools::install_version('dplyr', '1.0.6')" && \
    R -e "devtools::install_version('ggplot2', '3.3.6')" && \
    R -e "devtools::install_version('V8', '4.1.0')" && \
    R -e "devtools::install_version('Rcpp', '1.0.7')" && \
    R -e "devtools::install_version('RcppEigen', '0.3.3.9.1')" && \
    R -e "devtools::install_version('BH', '1.75.0-0')" && \
    R -e "devtools::install_version('RcppParallel', '5.1.4')" && \
    R -e "install.packages('StanHeaders', version = '2.26.13', repos = c('https://mc-stan.org/r-packages/', getOption('repos')))" && \
    R -e "install.packages('rstan', dependencies = TRUE)" && \
    R -e "install.packages('deSolve', dependencies = TRUE)" 

ADD * ./

EXPOSE 8787

CMD ["/init", "Rscript ./config.R"]
